# Generated by Django 5.0.1 on 2024-08-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
