# Generated by Django 5.0.1 on 2024-09-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_account_bank_account_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='iban',
            field=models.CharField(max_length=34),
        ),
    ]
