# Generated by Django 5.0.1 on 2024-09-09 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0016_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='size',
            name='is_available',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='reference_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.color')),
                ('images', models.ManyToManyField(blank=True, related_name='variations', to='webshop.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='webshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariationSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_sizes', to='webshop.productvariation')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.size')),
            ],
        ),
        migrations.AddField(
            model_name='productvariation',
            name='sizes',
            field=models.ManyToManyField(through='webshop.ProductVariationSize', to='webshop.size'),
        ),
        migrations.DeleteModel(
            name='ProductColorSize',
        ),
    ]
