# Generated by Django 5.0.1 on 2024-09-09 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0018_remove_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.CreateModel(
            name='ProductVariationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_variation_images/')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webshop.productvariation')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
