# Generated by Django 5.0.1 on 2024-09-09 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0019_remove_productvariation_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_posted', to='webshop.account'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webshop.productvariation'),
        ),
    ]
