# Generated by Django 5.0.1 on 2024-09-09 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0020_alter_comment_poster_alter_comment_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
