# Generated by Django 5.0.1 on 2024-09-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0022_alter_comment_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='home_address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='account',
            name='home_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='postal_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='street',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
