# Generated by Django 5.0.1 on 2024-09-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0023_rename_home_address_account_city_account_home_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='home_number',
            new_name='house_number',
        ),
    ]
