# Generated by Django 5.0.1 on 2024-09-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0025_remove_cart_created_at_remove_cartitem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='webshop.cartitem'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_cart', to='webshop.cart'),
        ),
    ]
