# Generated by Django 5.0.1 on 2024-09-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0026_cart_items_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PP', 'Plaćanje pouzećem'), ('IB', 'Internetsko bankarstvo')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
