# Generated by Django 5.0.1 on 2024-09-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0027_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PP', 'Plaćanje pouzećem'), ('IB', 'Internetsko bankarstvo')], default='PP', max_length=2),
        ),
    ]
