# Generated by Django 5.0.1 on 2024-09-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0028_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
