# Generated by Django 5.0.1 on 2024-09-12 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0029_remove_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='webshop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.productvariation')),
            ],
        ),
    ]
