# Generated by Django 5.0.1 on 2024-09-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0030_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variation_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webshop.productvariationsize'),
            preserve_default=False,
        ),
    ]
