# Generated by Django 5.0.1 on 2024-09-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0031_cartitem_product_variation_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_variation_size',
        ),
    ]
