# Generated by Django 5.0.1 on 2024-09-12 21:59

import webshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0034_alter_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=webshop.models.generate_order_number, editable=False, max_length=10, unique=True),
        ),
    ]
