# Generated by Django 5.0.1 on 2024-09-12 22:08

import webshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0035_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference_number',
            field=models.CharField(default=webshop.models.generate_order_number, editable=False, max_length=10, unique=True),
        ),
    ]
