# Generated by Django 5.0.1 on 2024-09-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0038_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
