# Generated by Django 5.0.1 on 2024-09-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0039_alter_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PP', 'Plaćanje pouzećem'), ('IB', 'Internetsko bankarstvo')], max_length=2),
        ),
    ]
