# Generated by Django 5.0.1 on 2024-09-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0041_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
    ]
