# Generated by Django 5.0.1 on 2024-09-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0042_remove_product_composition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='origin',
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
