# Generated by Django 5.0.1 on 2024-09-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0043_remove_product_origin_product_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
