# Generated by Django 5.0.1 on 2024-09-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0044_color_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
