# Generated by Django 5.0.1 on 2024-09-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0045_alter_color_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PP', 'Plaćanje pouzećem'), ('IB', 'Internetsko bankarstvo'), ('CC', 'Kartično plaćanje')], max_length=2),
        ),
    ]
